version: "3.8"

services:
  jekyll:
    image: bretfisher/jekyll-serve
    container_name: jekyll-site
    ports:
      - "4002:4000"
    volumes:
      - /root/dev.mikehathaway.com:/site
    restart: always

